version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: link_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres
    volumes:
      - ./migrations:/liquibase/changelog
    working_dir: /liquibase/changelog
    command:
      [
        "--url=jdbc:postgresql://postgres:5432/link_tracker_db",
        "--changeLogFile=master.xml",
        "--username=postgres",
        "--password=root",
        "update"
      ]

volumes:
  postgres_data:
