global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scrapper'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['scrapper:8101']

  - job_name: 'bot'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bot:8201']
