app:
  github-token: ${GITHUB_TOKEN}
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}

url:
  github-url: https://api.github.com
  stackoverflow-url: https://api.stackexchange.com/2.3/questions/{id}/answer


database:
  type: ORM

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.xml
    url: jdbc:postgresql://localhost:5433/link_tracker_db
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5433/link_tracker_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false


server:
  port: 8100

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
