app:
  telegram-token: ${TELEGRAM-TOKEN}

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

kafka:
  bootstrap-servers: localhost:9092
  group: bot-group
  topics:
    notification: notification

redis:
  duration: 30

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

