app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  group: bot-group
  topics:
    notification: notification

redis:
  duration: 30

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

